# generated by datamodel-codegen:
#   filename:  drawing_data.schema.json
#   timestamp: 2026-10-03T13:55:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class TitleBlock(BaseModel):
    part_number: str
    material: str
    hardness: str
    roughness: str
    general_tolerance: str
    drawing_number: str


class Status(Enum):
    PASS = 'PASS'
    WARN = 'WARN'
    FAIL = 'FAIL'
    UNMEASURED = 'UNMEASURED'


class Dimension(BaseModel):
    id: int
    balloon: str
    page: int | None = None
    datum_reference: str | None = None
    type: str
    type_label: str
    icon: str | None = None
    nominal: float
    nominal_str: str
    upper_tol: str
    lower_tol: str
    measured: str
    deviation: str
    status: Status
    feature_key: str | None = None
    gdt: str | None = None
    bbox: list[float] | None = Field(None, max_length=4, min_length=4)


class DrawingExtractionResult(BaseModel):
    success: bool
    error: str | None = None
    filename: str
    page_count: int | None = None
    raw_text_length: int | None = None
    title_block: TitleBlock
    datums: list[str]
    dimensions: list[Dimension]
