# generated by datamodel-codegen:
#   filename:  cad_metadata.schema.json
#   timestamp: 2026-10-04T16:32:12+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class FileFormat(Enum):
    step = 'step'
    stp = 'stp'
    stl = 'stl'
    obj = 'obj'


class Bbox(BaseModel):
    min: list[float] = Field(..., max_length=3, min_length=3)
    max: list[float] = Field(..., max_length=3, min_length=3)
    size: list[float] = Field(..., max_length=3, min_length=3)


class FeatureType(Enum):
    PLANE = 'PLANE'
    INTERNAL_CYLINDER = 'INTERNAL_CYLINDER'
    EXTERNAL_CYLINDER = 'EXTERNAL_CYLINDER'
    CONE = 'CONE'
    SPHERE = 'SPHERE'
    FREEFORM = 'FREEFORM'


class Feature(BaseModel):
    id: str
    feature_type: FeatureType
    nominal_dimension: float | None = None
    center: list[float] | None = Field(None, max_length=3, min_length=3)
    normal: list[float] | None = Field(None, max_length=3, min_length=3)
    area_or_length: float | None = None


class Alignment(BaseModel):
    base_plane_detected: bool | None = None
    table_clearance_min_z: float | None = None
    orientation_matrix: list[float] | None = Field(None, max_length=9, min_length=9)


class CadMetadata(BaseModel):
    model_name: str
    file_path: str | None = None
    file_format: FileFormat
    file_size_bytes: int | None = None
    vertex_count: int
    triangle_count: int
    bbox: Bbox
    features: list[Feature] | None = None
    alignment: Alignment | None = None
