# generated by datamodel-codegen:
#   filename:  inspection_plan.schema.json
#   timestamp: 2026-10-04T16:32:13+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Type(Enum):
    DATUM_PRIMARY = 'DATUM_PRIMARY'
    DATUM_SECONDARY = 'DATUM_SECONDARY'
    DATUM_TERTIARY = 'DATUM_TERTIARY'
    GEOMETRIC_TOL = 'GEOMETRIC_TOL'
    LINEAR_DIM = 'LINEAR_DIM'


class Priority(Enum):
    MANDATORY = 'MANDATORY'
    STANDARD = 'STANDARD'
    LEAN_FILTERED = 'LEAN_FILTERED'


class Status(Enum):
    PASS = 'PASS'
    WARN = 'WARN'
    FAIL = 'FAIL'
    SUSPECT = 'SUSPECT'
    PENDING = 'PENDING'


class Item(BaseModel):
    order: int
    item_id: str
    feature_id: str | None = None
    balloon_id: int | None = None
    type: Type
    datum_reference: list[str] | None = None
    priority: Priority
    feature_key: str | None = None
    characteristic: str | None = None
    nominal: float | None = None
    nominal_str: str | None = None
    upper_tol: float | None = None
    lower_tol: float | None = None
    measured: float | None = None
    status: Status
    operator_approved: bool | None = None
    approval_timestamp: str | None = None


class InspectionPlanPayload(BaseModel):
    plan_id: str
    created_at: str | None = None
    part_number: str
    cad_reference: str | None = None
    drawing_reference: str | None = None
    audit_hash: str
    items: list[Item]
