# generated by datamodel-codegen:
#   filename:  inspection_plan.schema.json
#   timestamp: 2026-10-03T10:05:47+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Status(Enum):
    PASS = 'PASS'
    WARN = 'WARN'
    FAIL = 'FAIL'
    SUSPECT = 'SUSPECT'
    PENDING = 'PENDING'


class Item(BaseModel):
    item_id: str
    balloon_id: int
    feature_key: str
    characteristic: str | None = None
    nominal: float
    upper_tol: float
    lower_tol: float
    measured: float | None = None
    status: Status
    operator_approved: bool
    approval_timestamp: str | None = None


class InspectionPlanPayload(BaseModel):
    plan_id: str
    created_at: str | None = None
    part_number: str
    cad_reference: str | None = None
    drawing_reference: str | None = None
    audit_hash: str
    items: list[Item]
