# generated by datamodel-codegen:
#   filename:  drawing_data.schema.json
#   timestamp: 2026-10-04T18:38:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class TitleBlock(BaseModel):
    part_number: str
    material: str
    hardness: str
    roughness: str
    general_tolerance: str
    drawing_number: str


class Status(Enum):
    PASS = 'PASS'
    WARN = 'WARN'
    FAIL = 'FAIL'
    UNMEASURED = 'UNMEASURED'


class Verification(Enum):
    RAW = 'RAW'
    PARSED = 'PARSED'
    DUAL_VERIFIED = 'DUAL_VERIFIED'
    CAD_VERIFIED = 'CAD_VERIFIED'
    HUMAN_VERIFIED = 'HUMAN_VERIFIED'
    NEEDS_REVIEW = 'NEEDS_REVIEW'
    CONFLICT = 'CONFLICT'
    UNVERIFIED = 'UNVERIFIED'


class Provenance(BaseModel):
    source_sha256: str | None = None
    page: int | None = None
    bbox: list[float] | None = Field(None, max_length=4, min_length=4)
    method: str | None = None
    extractor_version: str | None = None


class Dimension(BaseModel):
    id: int
    balloon: str
    page: int | None = None
    datum_reference: str | None = None
    type: str
    type_label: str
    icon: str | None = None
    nominal: float
    nominal_str: str
    upper_tol: str
    lower_tol: str
    measured: str
    deviation: str
    status: Status
    verification: Verification | None = 'PARSED'
    provenance: Provenance | None = None
    feature_key: str | None = None
    gdt: str | None = None
    op: str | None = None
    op_reason: str | None = None
    bbox: list[float] | None = Field(None, max_length=4, min_length=4)


class DrawingExtractionResult(BaseModel):
    success: bool
    error: str | None = None
    filename: str
    page_count: int | None = None
    raw_text_length: int | None = None
    title_block: TitleBlock
    datums: list[str]
    dimensions: list[Dimension]
