[package]
name = "ortho-router"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ortho-ast = { path = "../ortho-ast" }
ortho-kinematics = { path = "../ortho-kinematics" }
glam.workspace = true
approx.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
parry3d.workspace = true
