//! # ortho-emitter::calypso
//! 
//! Zeiss Calypso ASCII Özellik ve Tolerans (Prüfplan) Çıktı Motoru.
//! Calypso'nun "Özellik Tabanlı" (Feature-Oriented) mimarisine uygun olarak
//! unsurları, toleransları ve fitting stratejilerini ASCII formatında derler.

use std::fmt::Write;
use ortho_ast::{
    FeatureType, FittingAlgorithm, InspectionPlan, ProfileZoneDisposition, ToleranceType,
};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum CalypsoError {
    #[error("Kod biçimlendirme hatası: {0}")]
    FormatError(#[from] std::fmt::Error),
}

pub struct CalypsoEmitter;

impl Default for CalypsoEmitter {
    fn default() -> Self {
        Self::new()
    }
}

impl CalypsoEmitter {
    pub fn new() -> Self {
        Self
    }

    /// Nötr Teftiş Planından Zeiss Calypso uyumlu ASCII Prüfplan metni basar
    pub fn emit_calypso_ascii(&self, plan: &InspectionPlan) -> Result<String, CalypsoError> {
        let mut out = String::with_capacity(4096);

        // 1. BAŞLIK BİLGİLERİ (Prüfplan Header)
        writeln!(out, "; ZEISS CALYPSO PRUEFPLAN DEFINITION")?;
        writeln!(out, "; GENERATED BY NUPER ORTHO v0.1.0-alpha")?;
        writeln!(out, "; PART_NAME: {}", plan.part_name)?;
        writeln!(out, "; CAD_MODEL: {}", plan.cad_source_file)?;
        writeln!(out, "; UNITS: METRIC_MM")?;
        writeln!(out, "; -------------------------------------------------------------")?;
        writeln!(out)?;

        // 2. GEOMETRİK UNSURLAR (Geometrieelemente / Features)
        writeln!(out, "[FEATURES]")?;
        for feature in &plan.features {
            match feature.feature_type {
                FeatureType::Plane => {
                    writeln!(out, "FEATURE_TYPE: PLANE")?;
                    writeln!(out, "NAME: {}", feature.name)?;
                    writeln!(
                        out,
                        "NOM_BASE: {:.4}, {:.4}, {:.4}",
                        feature.centroid.x, feature.centroid.y, feature.centroid.z
                    )?;
                    writeln!(
                        out,
                        "NOM_NORMAL: {:.4}, {:.4}, {:.4}",
                        feature.normal_vector.x, feature.normal_vector.y, feature.normal_vector.z
                    )?;
                    writeln!(out, "AREA: {:.2}", feature.area)?;
                    writeln!(out, "END_FEATURE")?;
                    writeln!(out)?;
                }
                FeatureType::InternalCylinder => {
                    writeln!(out, "FEATURE_TYPE: CYLINDER_INTERNAL")?;
                    writeln!(out, "NAME: {}", feature.name)?;
                    writeln!(
                        out,
                        "NOM_CENTER: {:.4}, {:.4}, {:.4}",
                        feature.centroid.x, feature.centroid.y, feature.centroid.z
                    )?;
                    let axis = feature.axis_vector.unwrap_or(glam::DVec3::Z);
                    writeln!(out, "NOM_AXIS: {:.4}, {:.4}, {:.4}", axis.x, axis.y, axis.z)?;
                    writeln!(out, "NOM_DIAMETER: {:.4}", feature.diameter.unwrap_or(10.0))?;
                    writeln!(out, "NOM_LENGTH: {:.4}", feature.depth_or_length.unwrap_or(20.0))?;
                    writeln!(out, "END_FEATURE")?;
                    writeln!(out)?;
                }
                FeatureType::ExternalCylinder => {
                    writeln!(out, "FEATURE_TYPE: CYLINDER_EXTERNAL")?;
                    writeln!(out, "NAME: {}", feature.name)?;
                    writeln!(
                        out,
                        "NOM_CENTER: {:.4}, {:.4}, {:.4}",
                        feature.centroid.x, feature.centroid.y, feature.centroid.z
                    )?;
                    let axis = feature.axis_vector.unwrap_or(glam::DVec3::Z);
                    writeln!(out, "NOM_AXIS: {:.4}, {:.4}, {:.4}", axis.x, axis.y, axis.z)?;
                    writeln!(out, "NOM_DIAMETER: {:.4}", feature.diameter.unwrap_or(10.0))?;
                    writeln!(out, "NOM_LENGTH: {:.4}", feature.depth_or_length.unwrap_or(20.0))?;
                    writeln!(out, "END_FEATURE")?;
                    writeln!(out)?;
                }
                FeatureType::FreeformBSpline => {
                    writeln!(out, "FEATURE_TYPE: FREEFORM_SURFACE")?;
                    writeln!(out, "NAME: {}", feature.name)?;
                    writeln!(
                        out,
                        "NOM_CENTROID: {:.4}, {:.4}, {:.4}",
                        feature.centroid.x, feature.centroid.y, feature.centroid.z
                    )?;
                    writeln!(
                        out,
                        "NOM_NORMAL: {:.4}, {:.4}, {:.4}",
                        feature.normal_vector.x, feature.normal_vector.y, feature.normal_vector.z
                    )?;
                    writeln!(out, "AREA: {:.2}", feature.area)?;
                    writeln!(out, "END_FEATURE")?;
                    writeln!(out)?;
                }
                _ => {}
            }
        }

        // 3. TEFTİŞ ÖZELLİKLERİ VE FİTTİNG (Prüfmerkmale / Characteristics)
        writeln!(out, "[CHARACTERISTICS]")?;
        for tol in &plan.tolerances {
            let alg_str = match tol.recommended_fitting {
                FittingAlgorithm::ChebyshevMaximumInscribed => "EVALUATION: MAXIMUM_INSCRIBED (MIC)",
                FittingAlgorithm::ChebyshevMinimumCircumscribed => "EVALUATION: MINIMUM_CIRCUMSCRIBED (MCC)",
                FittingAlgorithm::MinimumZone => "EVALUATION: MINIMUM_ZONE",
                FittingAlgorithm::GaussLeastSquares => "EVALUATION: LEAST_SQUARES (GAUSS)",
            };

            match tol.tolerance_type {
                ToleranceType::Diameter => {
                    writeln!(out, "CHAR_TYPE: DIAMETER")?;
                    writeln!(out, "FEATURE_REF_ID: {}", tol.feature_id)?;
                    writeln!(out, "NOMINAL: {:.4}", tol.nominal_value)?;
                    writeln!(out, "UPPER_TOL: +{:.4}", tol.upper_tolerance)?;
                    writeln!(out, "LOWER_TOL: {:.4}", tol.lower_tolerance)?;
                    writeln!(out, "{}", alg_str)?;
                    writeln!(out, "END_CHAR")?;
                    writeln!(out)?;
                }
                ToleranceType::Position => {
                    writeln!(out, "CHAR_TYPE: TRUE_POSITION")?;
                    writeln!(out, "FEATURE_REF_ID: {}", tol.feature_id)?;
                    writeln!(out, "TOLERANCE_ZONE: {:.4}", tol.upper_tolerance)?;
                    writeln!(out, "MATERIAL_CONDITION: RFS")?;
                    writeln!(out, "END_CHAR")?;
                    writeln!(out)?;
                }
                ToleranceType::ProfileOfSurface => {
                    writeln!(out, "CHAR_TYPE: SURFACE_PROFILE")?;
                    writeln!(out, "FEATURE_REF_ID: {}", tol.feature_id)?;
                    if let Some(ProfileZoneDisposition::UnequallyDisposed {
                        total_width,
                        outward_offset,
                    }) = tol.profile_disposition
                    {
                        writeln!(out, "TOLERANCE_ZONE: {:.4}", total_width)?;
                        writeln!(out, "DISPOSITION: UNEQUALLY_DISPOSED")?;
                        writeln!(out, "OUTWARD_OFFSET: {:.4}", outward_offset)?;
                        writeln!(out, "INWARD_OFFSET: -{:.4}", total_width - outward_offset)?;
                    } else {
                        writeln!(
                            out,
                            "TOLERANCE_ZONE: {:.4}",
                            tol.upper_tolerance - tol.lower_tolerance
                        )?;
                        writeln!(out, "DISPOSITION: BILATERAL_SYMMETRIC")?;
                    }
                    let datums_str: Vec<String> =
                        tol.datum_precedence.iter().map(|d| format!("{:?}", d)).collect();
                    if !datums_str.is_empty() {
                        writeln!(out, "DATUMS: {}", datums_str.join(", "))?;
                    }
                    writeln!(out, "{}", alg_str)?;
                    writeln!(out, "END_CHAR")?;
                    writeln!(out)?;
                }
                _ => {}
            }
        }

        // 4. ASME Y14.5 BİLEŞİK KONUM TOLERANSLARI (COMPOSITE FCF)
        for c_tol in &plan.composite_tolerances {
            writeln!(out, "CHAR_TYPE: COMPOSITE_TRUE_POSITION")?;
            writeln!(out, "NAME: {}", c_tol.name)?;
            let fids: Vec<String> = c_tol.feature_ids.iter().map(|id| id.to_string()).collect();
            writeln!(out, "FEATURE_REFS: {}", fids.join(", "))?;
            writeln!(out, "PLTZF_ZONE: {:.4}", c_tol.pltzf.tolerance_value)?;
            let p_dat: Vec<String> = c_tol
                .pltzf
                .datum_precedence
                .iter()
                .map(|d| format!("{:?}", d))
                .collect();
            if !p_dat.is_empty() {
                writeln!(out, "PLTZF_DATUMS: {}", p_dat.join(", "))?;
            }
            writeln!(out, "FRTZF_ZONE: {:.4}", c_tol.frtzf.tolerance_value)?;
            let f_dat: Vec<String> = c_tol
                .frtzf
                .datum_precedence
                .iter()
                .map(|d| format!("{:?}", d))
                .collect();
            if !f_dat.is_empty() {
                writeln!(out, "FRTZF_DATUMS: {}", f_dat.join(", "))?;
            }
            writeln!(out, "END_CHAR")?;
            writeln!(out)?;
        }

        writeln!(out, "[END_PRUEFPLAN]")?;
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use glam::DVec3;
    use ortho_ast::{DatumReferenceFrame, GeometricFeature, ToleranceConstraint};

    #[test]
    fn test_calypso_ascii_export() {
        let drf = DatumReferenceFrame::new_3_2_1("PCS_1", 1, 2, 3);
        let mut plan = InspectionPlan::new("VALVE_OP10", "valve.step", drf);

        let hole = GeometricFeature::new_internal_cylinder(
            4,
            "CYL_BORE_20",
            DVec3::new(50.0, 50.0, 25.0),
            DVec3::Z,
            20.0,
            30.0,
            1884.0,
            10.0,
        )
        .unwrap();
        plan.features.push(hole);
        plan.tolerances
            .push(ToleranceConstraint::new_h7_hole(101, 4, 20.0, 0.021));

        let emitter = CalypsoEmitter::new();
        let ascii = emitter.emit_calypso_ascii(&plan).expect("Calypso emit failed");

        assert!(ascii.contains("ZEISS CALYPSO PRUEFPLAN DEFINITION"));
        assert!(ascii.contains("FEATURE_TYPE: CYLINDER_INTERNAL"));
        assert!(ascii.contains("CHAR_TYPE: DIAMETER"));
        assert!(ascii.contains("EVALUATION: MAXIMUM_INSCRIBED (MIC)"));
        assert!(ascii.contains("[END_PRUEFPLAN]"));
    }

    #[test]
    fn test_calypso_freeform_and_composite() {
        use ortho_ast::{CompositeTolerance, DatumLabel, ProfileZoneDisposition};

        let drf = DatumReferenceFrame::new_3_2_1("PCS_1", 1, 2, 3);
        let mut plan = InspectionPlan::new("TURBINE_BLADE", "blade.step", drf);

        let blade = GeometricFeature::new_freeform_surface(
            1,
            "BLADE_SUCTION_FACE",
            DVec3::new(20.0, 30.0, 50.0),
            DVec3::Y,
            2400.0,
            2.5,
        )
        .unwrap();

        let h1 = GeometricFeature::new_internal_cylinder(
            11,
            "ROOT_PIN_1",
            DVec3::new(5.0, 0.0, 0.0),
            DVec3::Z,
            6.0,
            12.0,
            75.0,
            3.0,
        )
        .unwrap();

        let h2 = GeometricFeature::new_internal_cylinder(
            12,
            "ROOT_PIN_2",
            DVec3::new(25.0, 0.0, 0.0),
            DVec3::Z,
            6.0,
            12.0,
            75.0,
            3.0,
        )
        .unwrap();

        plan.features.push(blade);
        plan.features.push(h1);
        plan.features.push(h2);

        let profile_tol = ToleranceConstraint::new_surface_profile(
            50,
            1,
            0.50,
            ProfileZoneDisposition::UnequallyDisposed {
                total_width: 0.50,
                outward_offset: 0.10,
            },
            vec![DatumLabel::A, DatumLabel::B],
        );
        plan.tolerances.push(profile_tol);

        let comp_pos = CompositeTolerance::new_composite_position(
            60,
            "ROOT_PINS_COMP",
            vec![11, 12],
            0.40,
            vec![DatumLabel::A, DatumLabel::B],
            0.08,
            vec![DatumLabel::A],
        );
        plan.composite_tolerances.push(comp_pos);

        let emitter = CalypsoEmitter::new();
        let ascii = emitter.emit_calypso_ascii(&plan).expect("Calypso emit failed");

        assert!(ascii.contains("FEATURE_TYPE: FREEFORM_SURFACE"));
        assert!(ascii.contains("CHAR_TYPE: SURFACE_PROFILE"));
        assert!(ascii.contains("DISPOSITION: UNEQUALLY_DISPOSED"));
        assert!(ascii.contains("OUTWARD_OFFSET: 0.1000"));
        assert!(ascii.contains("CHAR_TYPE: COMPOSITE_TRUE_POSITION"));
        assert!(ascii.contains("PLTZF_ZONE: 0.4000"));
        assert!(ascii.contains("FRTZF_ZONE: 0.0800"));
    }
}
